export const textColor = {
  gray5: 'text-gray-5',
  gray10: 'text-gray-10',
  gray11: 'text-gray-11',
  gray13: 'text-gray-13',
  gray15: 'text-gray-15',
  gray20: 'text-gray-20',
  gray25: 'text-gray-25',
  gray30: 'text-gray-30',
  gray35: 'text-gray-35',
  gray40: 'text-gray-40',
  gray45: 'text-gray-45',
  gray50: 'text-gray-50',
  gray55: 'text-gray-55',
  gray60: 'text-gray-60',
  gray65: 'text-gray-65',
  gray70: 'text-gray-70',
  gray90: 'text-gray-90',
  blue10: 'text-blue-10',
  orange1: 'text-orange-1',
  orange2: 'text-orange-2',
  orange3: 'text-orange-3',
  orange4: 'text-orange-4',
  orange5: 'text-orange-5',
  orange6: 'text-orange-6',
  orangeHover: 'text-orange-hover',
  red: 'text-red',
  yellow: 'text-yellow',
  login: 'text-login',
  green: 'text-green',
  success: 'text-success',
  success2: 'text-success2',
  alert: 'text-alert',
  alerthover: 'text-alerthover',
  brown: 'text-brown',
  brownModal: 'text-brownModal',
  white: 'text-white',
} as const;

export const bgColor = {
  orange1: 'bg-orange-1',
  orange2: 'bg-orange-2',
  orange3: 'bg-orange-3',
  orange4: 'bg-orange-4',
  orange5: 'bg-orange-5',
  orange6: 'bg-orange-6',
  orangeHover: 'bg-orange-hover',
  yellow: 'bg-yellow',
  gray20: 'bg-gray-20',
  gray15: 'bg-gray-15',
  alert: 'bg-alert',
  alertHover: 'bg-alerthover',
} as const;

export type KeyOfColor = keyof typeof textColor;
